version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html # apacheのデフォルトのDocumentRootにphpファイルをマウント

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
